class IngredientsValues{
  static final Map<String, String> ingredientsValues = {
    'AloeBarbadensisLeafJuice(2%)': 'Aloe vera er effektiv til behandling af huller, da den hæmmer væksten af bakterier, der forårsager tandbrydning. Denne plante fremskynder heling og reducerer smerte forbundet med blister eller sår på læberne eller i munden. Konklusionen er, at både aloe vera gel og aloe vera juice kan bevare din mundsundhed',
    'Amyloglucosidase': 'Enzymer og proteiner, kan styrke de naturlige spytdfensemekanismer ved at øge niveauerne af lysozym og hydrogenperoxid in vivo og hypothiocyanit in vitro samt reducere væksten og levedygtigheden af ​​mundbakterier i mikrobiologiske modeller.',
    'Anethole': 'Aroma',
    'Aqua': 'Opløser stoffer eller ingredienser.',
    'Arginine': 'En aminosyre, der kan bruges i tandpasta for at hjælpe med at neutralisere syrer i munden og støtte remineralisering af tandemaljen.',
    'Aroma': 'Giver friskere ånde og bedre produktsmag',
    'Alcohol': 'Tilføjes tandpasta for at fungere som et opløsningsmiddel og for at give en forfriskende fornemmelse. Det er vigtigt at bemærke, at nogle mennesker kan være følsomme over for alkohol, og det kan forårsage irritation.',
    'AniseAlcohol': 'En naturlig forbindelse, der findes i anis og lignende planter, og det kan bruges som et aromastof i tandpasta.',
    'BenzylAlcohol': 'Har antimikrobielle egenskaber og kan bruges som konserveringsmiddel. Beskytter produkterne mod bakterie-, gær- og mugvækst.',
    'Bisabolol': 'En naturlig forbindelse, der findes i kamilleolie, og det kan tilføjes tandpasta for sine beroligende og antiinflammatoriske egenskaber.',
    'Calcium': 'Calcium er en mineralforbindelse, og det kan tilføjes tandpasta for at styrke tandemaljen og hjælpe med remineralisering af tænderne.',
    'CalciumCarbonate': 'Hjælper med at rense og polere tænderne.',
    'CalciumPyrophosphate': 'En forbindelse, der kan bruges i tandpasta som et let slibemiddel for at hjælpe med at fjerne pletter og polere tænderne.',
    'Carbomer': 'En type polymer, der anvendes som fortykningsmiddel og stabilisator i tandpasta. Det hjælper med at opretholde konsistensen af tandpastaen.',
    'Carboxylesterase': 'Dette er et enzym, der kan have en rolle i nedbrydning af visse kemiske forbindelser. I tandpasta kan det muligvis bruges som et enzymatisk supplement.',
    'Carrageenan': 'En polysakkarid udvundet fra rødalger, der bruges som fortykningsmiddel og stabilisator i tandpasta. Det hjælper også med at give tandpastaen en jævn konsistens.',
    'Carvone': 'En naturlig forbindelse, der findes i visse æteriske olier, såsom kommen og dild. Carvone kan tilføjes til tandpasta for at give en naturlig smag og aroma.',
    'CelluloseGum': 'En naturlig forbindelse, der findes i visse æteriske olier, såsom kommen og dild. Carvone kan tilføjes til tandpasta for at give en naturlig smag og aroma.',
    'Cellulosegum': 'En naturlig forbindelse, der findes i visse æteriske olier, såsom kommen og dild. Carvone kan tilføjes til tandpasta for at give en naturlig smag og aroma.',
    'CetearylAlcohol': 'En blanding af cetyl og stearylalkohol, som fungerer som et fortykningsmiddel og stabilisator i tandpasta. Giver den ønskede konsistens og kan også fungere som en emulgator for at blande vand- og oliebaserede ingredienser.',
    'CentellaAsiaticaExtract': 'Også kaldt; Gotu Kola, er dette et planteekstrakt, der traditionelt er blevet brugt for dets potentielle hudhelende egenskaber. I tandpasta kan det tilføjes for at give beroligende egenskaber og muligvis understøtte mundhelse.',
    'CetylpyridiniumChloride': 'Antimikrobielle egenskaber, der ofte bruges i tandplejeprodukter som et middel til at hjælpe med at kontrollere bakterievækst i munden. Det kan bidrage til at reducere plak og dårlig ånde.',
    'ChondrusCrispus': 'Chondrus Crispus er en rød alge, hvorfra carrageenan udvindes og bruges i kosmetik på grund af dens gele- og bindningsegenskaber',
    'ChlorhexidineDigluconate': 'Antiseptisk,hjælper med at kontrollere bakterievækst og plak. Det har antibakterielle egenskaber og kan bidrage til at opretholde mundhygiejne.',
    'CI42053': 'Grønt farvestof',
    'CI42090': 'Blåt farvestof',
    'CI73360': 'Rødt farvestof',
    'CI74160': 'Blåt farvestof',
    'CI74260': 'Grønt farvestof',
    'CI77491': 'Rødt jernoxid',
    'CI77891': 'Hvidt farvestof',
    'CI77492': 'Gul jernoxid',
    'Cinnamal': 'En aromatisk forbindelse, der giver en cinnamonduft og -smag. Det kan anvendes som smagsstof i tandpasta.',
    'CitrusAurantiumAmaraFruit': 'Henviser til bitter appelsinfrugt. Det kan bruges som smagsstof eller for at tilføje duft til tandpastaen.',
    'CitricAcid': 'En organisk syre, der bruges til at justere pH-niveauet i tandpastaen og kan have antibakterielle egenskaber.',
    'CitrusLimonPeelOil': 'Citronskrælolie, der giver tandpastaen en citronsmag og kan bidrage til at forfriske ånde.',
    'CocamidopropylBetaine': 'En overfladeaktiv substans, der bruges som skummiddel og rensemiddel i tandpasta.',
    'Colostrum': 'Råmælk, normalt fra køer. Det kan tilføjes tandpasta for dets potentielle antibakterielle og antiinflammatoriske egenskaber.',
    'Copolymer': 'Dette er en bred kategori af polymerer.Det kan bruges som et fortykningsmiddel eller et bindemiddel.',
    'D-Limonene': 'En naturlig forbindelse findes i citrusolier, der kan tilføjes for smag og duft.',
    'DecylGlucoside': 'En mild overfladeaktiv substans, der bruges som skummiddel og rensemiddel.',
    'DicalciumPhosphateDihydrate': 'En form for calciumfosfat, der kan anvendes til at polere tænder og bidrage til at fjerne pletter.',
    'Dioxide': 'Det kan referere til forskellige forbindelser, herunder titandioxid, der anvendes som et hvidt pigment i tandpasta.',
    'DisodiumPhosphate': 'En forbindelse, der kan bruges til at justere pH-niveauet i tandpasta.',
    'DisodiumC12-14Pareth-2Sulfosuccinate': 'En overfladeaktiv substans, der kan bruges som skummiddel og rensemiddel.',
    'DisodiumPyrophosphate': 'En forbindelse, der kan bidrage til at reducere dannelsen af tandsten ved at binde calciumioner.',
    'Eucalyptol': 'En naturlig forbindelse, der findes i eukalyptusolie, og det kan tilføjes tandpasta for dets antiseptiske egenskaber og mintagtige smag.',
    'EchinaceaPurpureaRootExtract': 'Et ekstrakt fra echinacea-rødder, der kan tilføjes for dets potentielle antiinflammatoriske og immunstimulerende egenskaber.',
    'EthylMenthaneCarboxamide': 'En syntetisk forbindelse, der kan bruges som et kølemiddel i tandpasta for at give en frisk fornemmelse.',
    'Eugenol': 'En naturlig forbindelse findes i nellikeolie, der kan anvendes som smagsstof og for sin antimikrobielle virkning.',
    'Glucose': 'En simpel sukker, der kan bruges som et sødemiddel i tandpasta.',
    'GlucoseOxidase': 'Et enzym, der kan have antibakterielle egenskaber.',
    'Glycerin': 'Hjælper med at opløse ingredienserne og forebygge udtørring eller hærdning, så produktet forbliver jævnt.',
    'HarpagophytumProcumbensRootExtract': 'Potentielle evne til at lindre inflammation og muligvis støtte i behandlingen af tandkødsproblemer. Det kan også tilføje en naturlig smag eller aroma til tandpastaen',
    'HydratedSilica': 'Hjælper med at rense og polere tænderne.',
    'Silica': 'Silica: En slags slipmiddel og fortykningsmiddel, der bruges i tandpasta for at bidrage til at fjerne pletter og polere tænderne.',
    'HydrogenatedCastorOil': 'En modificeret form af ricinusolie, der kan bruges som en emulgator eller fortykningsmiddel.',
    'HydrogenatedLecithin': 'En modificeret form af lecithin, der kan bruges som emulgator eller fortykningsmiddel i tandpasta.',
    'HydrogenatedStarchHydrolysate': 'En modificeret form af stivelse, der kan bruges som et fortykningsmiddel og sødemiddel i tandpasta.',
    'HydrogenPeroxide': 'En oxidationsmiddel, der kan bruges til at hjælpe med at blege tænder og reducere pletter.',
    'Hydroxyapatite': 'En naturlig komponent af tandemaljen, der kan tilføjes tandpasta for at styrke tandoverfladen og hjælpe med remineralisering.',
    'Hydroxyethylcellulose': 'Et fortykningsmiddel og emulgator, der bidrager til tandpastaens konsistens og stabilitet.',
    'Hydroxypropylmethylcellulose': 'En form for cellulose, der bruges som fortykningsmiddel og stabilisator i tandpasta.',
    'Isomalt': 'En sukkeralkohol, der kan bruges som et sødemiddel i tandpasta.',
    'Isomenthone': 'En kemisk forbindelse, der bidrager til mentholsmagen og aromaen i tandpasta.',
    'Ironoxide': 'Et mineralpigment, der kan bruges til at farve tandpastaen.',
    'Lactoferrin': 'En naturlig komponent, der findes i mælk og har antimikrobielle egenskaber, der kan hjælpe med at kontrollere bakterievækst i munden.',
    'Lactoperoxidase': 'Et enzym, der findes i mælk og spyt, og det kan have antibakterielle egenskaber.',
    'LaurylGlucoside': 'En mild overfladeaktiv substans, der kan bruges som et skummiddel og rensemiddel i tandpasta.',
    'Linalool': 'Et naturligt forekommende enzym, der findes i spyt og tårevæske. Lysozyme har antibakterielle egenskaber og kan hjælpe med at kontrollere bakterievækst i munden. Det tilføjes nogle gange tandpasta for at styrke den antimikrobielle virkning.',
    'Lysozyme': 'Et naturligt forekommende enzym, der findes i spyt og tårevæske. Lysozyme har antibakterielle egenskaber og kan hjælpe med at kontrollere bakterievækst i munden. Det tilføjes nogle gange tandpasta for at styrke den antimikrobielle virkning.',
    'Limonene': 'Limonene, a cyclic monoterpene that is the primary chemical constituent of several citrus oils, has shown to be useful in dental applications. Human clinical research suggests that toothpaste containing limonene may help to brighten teeth and remove stains.',
    'Kaliumnitrat': 'En forbindelse, der ofte anvendes i tandpasta til at lindre tandfølsomhed ved at blokere nerveimpulser. Det er en almindelig ingrediens i tandpasta til personer med følsomme tænder.',
    'Maltodextrin': 'En forbindelse, der ofte anvendes i tandpasta til at lindre tandfølsomhed ved at blokere nerveimpulser. Det er en almindelig ingrediens i tandpasta til personer med følsomme tænder.',
    'Mannitol': 'Et sukkeralkohol, der bruges som et sødemiddel og kan give en sød smag til tandpastaen. Mannitol kan også have en kølende effekt.',
    'Menthol': 'Et sukkeralkohol, der bruges som et sødemiddel og kan give en sød smag til tandpastaen. Mannitol kan også have en kølende effekt.',
    'Metabisulfite': 'Et sukkeralkohol, der bruges som et sødemiddel og kan give en sød smag til tandpastaen. Mannitol kan også have en kølende effekt.',
    'MagnesiumAluminumSilicate': 'Fortyknings- eller stabiliseringsmiddel, som giver pastaen den ønskede konsistens.',
    'MenthaPiperita(Peppermint)': 'Pebermynteolie, der bruges til at give tandpastaen en frisk og kølig smag. Det har også antibakterielle egenskaber og kan hjælpe med at forfriske åndedrættet.',
    'Mentha Viridis (Spearmint)': 'Spearmintolie, der anvendes for sin friske og milde myntesmag. Ligesom pebermynte kan det også have antibakterielle egenskaber og en forfriskende virkning.',
    'Menthone': 'En kemisk forbindelse, der bidrager til smagen og duften af pebermynte. Det har også en kølende effekt.',
    'MenthylLactate': 'En ester af menthol og mælkesyre, der kan bruges til at tilføje en kølende effekt til tandpastaen.',
    'MethylDiisopropyl': 'Det kan referere til en gruppe kemiske forbindelser. Det er vigtigt at kende den specifikke form og funktion for at give en nøjagtig vurdering.',
    'MenthylAcetate': 'En ester af menthol og eddikesyre, der kan bidrage til smagen og aromaen af tandpastaen.',
    'Microcrystalline': 'Kan være en form for voks eller fortykningsmiddel.',
    'Mica': 'Et mineral, der kan bruges som et slipmiddel og give tandpastaen en glat konsistens.',
    'Natriumbenzoat': 'En konserveringsmiddel, der hjælper med at forhindre vækst af skadelige bakterier og svampe i tandpastaen.',
    'Natriumfluorid': 'En fluorideforbindelse, der anvendes til at styrke tandemaljen og hjælpe med at forhindre karies.',
    'o-Cymen-5-ol': 'En antimikrobiel og antibakteriel forbindelse, der kan hjælpe med at kontrollere bakterievækst i mundhulen.',
    'Parfum': 'En blanding af duftstoffer, der tilsættes tandpastaen for at forbedre smagen og mundfølelsen.',
    'Panthenol': 'En form af vitamin B5, der kan bidrage til at opretholde sundheden for tandkød og slimhinder.',
    'PEG-6': 'En type af polyethylenglycol (PEG), der anvendes som emulgatorer og fortykningsmidler',
    'PEG-8': 'En type af polyethylenglycol (PEG), der anvendes som emulgatorer og fortykningsmidler',
    'PEG-12': 'En type af polyethylenglycol (PEG), der anvendes som emulgatorer og fortykningsmidler',
    'PEG-13': 'En type af polyethylenglycol (PEG), der anvendes som emulgatorer og fortykningsmidler',
    'PEG-40': 'En type af polyethylenglycol (PEG), der anvendes som emulgatorer og fortykningsmidler',
    'PentasodiumTriphosphate': 'En forbindelse, der kan hjælpe med at reducere dannelsen af tandsten ved at binde calciumioner.',
    'PhosphoricAcid': 'En syre, der kan anvendes til at justere pH-niveauet i tandpastaen.',
    'Poloxamer105': 'Emulgatorer, der hjælper med at blande vand- og oliebaserede ingredienser i tandpastaen.',
    'Poloxamer407': 'Emulgatorer, der hjælper med at blande vand- og oliebaserede ingredienser i tandpastaen.',
    'Polylysine': 'En aminosyre, der kan bruges som et fortykningsmiddel og stabilisator.',
    'Polyethylene': 'Disse kan være brugt som slibemiddel eller til at give tandpastaen en let slibende virkning',
    'Polysobate80': 'En emulgator, der hjælper med at blande forskellige ingredienser i tandpastaen.',
    'Potassium': 'Kalium kan have forskellige funktioner, herunder at fungere som en smagsforstærker eller fortykningsmiddel.',
    'PotassiumAcesulfame': 'En kunstig sødestof, der kan bruges til at give tandpastaen en sød smag',
    'PotassiumNitrate': 'Kaliumnitrat i tandpasta bruges primært til at hjælpe med at lindre og behandle tandfølsomhed. Faktisk anser adskillige reguleringsorganer over hele verden kaliumnitrat for både sikkert og effektivt til behandling af tandfølsomhed',
    'PotassiumSorbate': 'Et konserveringsmiddel, der bruges til at forlænge holdbarheden af tandpasta ved at hæmme væksten af skadelige mikroorganismer.',
    'PotassiumChloride': 'Bruges ofte til at reducere tandkødsirritation og for at give smag til tandpasta.',
    'PotassiumThiocyanate': 'Dette er et enzym, der kan hjælpe med at bekæmpe bakterier i munden.',
    'Propionamide': 'Dette kan være et fortykningsmiddel eller et bindemiddel og hjælpe med at bevare konsistensen af tandpastaen.',
    'PropyleneGlycol': 'En fugtgivende og fortykningsmiddel, der hjælper med at bevare fugtigheden i tandpastaen.',
    'PVP': 'PVP (Polyvinylpyrrolidon): Anvendes som et bindemiddel og fortykningsmiddel og hjælper med at forhindre tandpasta i at tørre ud.',
    'PunicaGranatumFruitExtract': 'Almindeligvis kendt som granatæbleekstrakt, og det bruges ofte på grund af dets antioxidante egenskaber.',
    'Pyrophosphate': 'Dette er en ingrediens, der ofte anvendes til at reducere dannelsen af tandsten og plak ved at binde calciumioner.',
    'Sodium': 'Ofte brugt i form af forskellige forbindelser som smag, fortykningsmiddel eller til at justere pH-niveauet.',
    'SodiumAlgin': 'Dette er en fortykningsmiddel og emulgator, der kan hjælpe med at give tandpastaen den ønskede konsistens.',
    'SodiumBicarbonate': 'Almindeligt kendt som bagepulver, og det kan hjælpe med at fjerne pletter og give tandpastaen en lettere slibende virkning.',
    'SodiumBisulfite': 'Dette kan fungere som en antioxidant og konserveringsmiddel.',
    'SodiumBenzoate': 'For at hæmme væksten af mikroorganismer i tandpasta tilføjer producenter normalt en vis mængde konserveringsmidler. Når man tager højde for den antimikrobielle effekt, sikkerhed og pris, er natriumbenzoat ofte det bedre valg sammenlignet med andre almindeligt anvendte konserveringsmidler i tandpasta',
    'SodiumCarbonate': 'Hjælper med at rense og polere tænderne.',
    'SodiumCaseinate': 'En form for natriumsalt af casein, et protein, der findes i mælk. Det bruges ofte som et fortykningsmiddel og stabilisator i tandpasta for at give den ønskede konsistens.',
    'SodiumChloride': 'En vigtig ingrediens i salttandpasta er natriumchlorid, også kendt som bordssalt. Saltet fungerer som et blidt slidemiddel, der hjælper med at fjerne pletter fra tænderne og giver smag.',
    'SodiumCitrate': 'En form for natriumsalt af citronsyre, der anvendes i tandpasta for at justere pH-niveauet og som et surhedsregulerende middel.',
    'SodiumFluoride': 'Styrker tandemaljen og hjælper med at forhindre karies.',
    'SodiumGluconate': 'Natriumgluconat spiller en vigtig rolle som stabilisator for fluordistributionsystemer i tandpastasammensætninger. Det reagerer med natriumfluorid for at danne stannousfluorid, der fungerer som den aktive molekyle i fluordistributionsystemet.',
    'SodiumHexametaphosphate': 'Polymeren inkluderet i Oral-B Pro-Expert tandpasta, natriumhexametafosfat, er bevist at hjælpe med at give det vigtige vindende smil ved at reducere ekstrinsisk farvning. Den fungerer ved at kombinere både mekanismer til forebyggelse og fjernelse af pletter.',
    'SodiumHydroxide': 'Sodium peroxide tilsættes din tandpasta for at hjælpe i tandblegningsprocessen. Den består af brintperoxid og natriumcarbonat (vaskesoda), der blegner tænderne og dræber bakterier.',
    'SodiumLaurylSulfate': 'Skummiddel, som hjælper med at fjerne snavs.',
    'SodiumMethylparaben': 'Anvendes for at forhindre vækst af bakterier og svampe. Dog er brugen af parabener blevet diskuteret på grund af bekymringer for deres potentielle hormonforstyrrende virkning.',
    'SodiumMethylCocoylTaurate': 'En overfladeaktiv substans, der fungerer som et rensemiddel og skummiddel i tandpasta. Det er en mild ingrediens, der ofte bruges i personlige plejeprodukter.',
    'SodiumPhosphosilicate(NOVAMIN®)': 'Er en patenteret ingrediens, der indeholder natrium- og phosphatsilikater. Det hævdes at have remineraliserende egenskaber, der kan hjælpe med at styrke tandemaljen og reparere små skader på tænderne.',
    'SodiumSaccharin': 'Er et patenteret ingrediens, der indeholder natrium- og phosphatsilikater. Det hævdes at have remineraliserende egenskaber, der kan hjælpe med at styrke tandemaljen og reparere små skader på tænderne.',
    'Sorbitol': 'Hjælper med at opløse ingredienserne og forebygge udtørring eller hærdning, så produktet forbliver jævnt.',
    'Starch': 'Kan anvendes som et fortykningsmiddel og stabilisator i tandpasta for at give den ønskede konsistens.',
    'StannousChloride': 'Bruges ofte til at hjælpe med at reducere tandkødssygdomme og tandsten, og det har antibakterielle egenskaber.',
    'StannousFluoride': 'En fluorideforbindelse, der anvendes til at styrke tandemaljen og hjælpe med at forhindre karies.',
    'StearicAcid': 'En fedtsyre, der kan bruges som et fortykningsmiddel og emulgator for at stabilisere tandpastablandingen.',
    'Steareth-30': 'En emulgator, der hjælper med at blande vand- og oliebaserede ingredienser i tandpastaen.',
    'SteviaRebaudianaExtract': 'En naturlig sødestof, der kan bruges til at forbedre smagen af tandpasta uden at tilføje sukker eller kunstige sødestoffer.',
    'Sucralose': 'En kunstig sødestof, der bruges til at give en sød smag uden at bidrage til tandkaries.',
    'Tetrasodium': 'Ofte brugt som et konserveringsmiddel og stabilisator i kosmetiske produkter.',
    'TetrasodiumPyrophosphate': 'En forbindelse, der kan hjælpe med at forhindre dannelse af tandsten ved at binde calciumioner.',
    'Tinfluorid': 'En fluorideforbindelse, der anvendes til tandpleje for at styrke tandemaljen og beskytte mod karies.',
    'TinOxide': 'Kan bruges som en slipmiddeleffekt i tandpasta og hjælpe med at fjerne pletter.',
    'Titanium': 'Kan bruges som et slipmiddel eller pigment i tandpasta for at forbedre dets udseende.',
    'TitaniumDioxide': 'En hvid pigment, der bruges til at give tandpasta en hvid farve.',
    'Thiocyanate': 'Kan have antibakterielle egenskaber og bidrage til bekæmpelse af mundinfektioner.',
    'Tocopherol': 'En form for vitamin E, der kan have antioxidantegenskaber.',
    'TocopherylAcetate': 'En derivat af vitamin E, der bruges for dets antioxidantegenskaber.',
    'Triacetin': 'En lugtfri og farveløs væske, der kan bruges som en blødgører eller opløsningsmiddel.',
    'TrisodiumPhosphate': 'Anvendes som en pH-regulator og kan bidrage til at fjerne pletter fra tænderne.',
    'UrticaDioicaLeafExtract': 'Ekstrakt fra nældeblad, som kan have antiinflammatoriske egenskaber.',
    'XanthanGum': 'Et naturligt fortykningsmiddel, der hjælper med at opretholde tandpastaens konsistens',
    'Xylitol': 'Et naturligt sukkeralkohol, der bruges til at give sødme og kan have kariesforebyggende egenskaber.',
    'ZeaMays': 'Maisstivelse, som kan fungere som et fortykningsmiddel og stabilisator.',
    'ZincCitrate': 'En form af zink, der kan bidrage til at reducere plak og forebygge tandkaries.',
    'ZincLactate': 'En anden form af zink, der kan have antibakterielle egenskaber og hjælpe med at kontrollere dårlig ånde.',
    'ZincGluconate': 'Zink er formuleret til orale sundhedsprodukter for at reducere plak og dårlig ånde samt hæmme dannelsen af tandsten. Det har god oral substans, og forhøjede koncentrationer kan vare ved i mange timer i plak og spyt efter brug af mundskyllevand og tandpasta.',
    'ZincOxide': 'Bruges ofte i tandpasta som et slipmiddel for at hjælpe med at fjerne pletter fra tænderne. Det kan også have antibakterielle egenskaber og hjælpe med at kontrollere dårlig ånde.',
    'ZincChloride': 'En form af zink, der kan bidrage til at reducere plak og bakterievækst i munden. Det kan også have en astringerende effekt.',
    'ZingiberOfficinaleRootExtract': 'Dette er ingefærrodsekstrakt, og det kan tilføjes tandpasta for dets potentielle antiinflammatoriske og antimikrobielle egenskaber.',
    'Ubiquinone': 'Også kendt som coenzym Q10, er ubiquinone et antioxidant, der kan bidrage til at støtte sundheden for tandkød og mundvæv. Det kan også hjælpe med at opretholde cellesundheden og modvirke inflammation.',
  };
}